package com.vineyards.deerPlanner.guests.outbound;

import com.vineyards.deerPlanner.guests.application.port.GuestGroupOutPort;
import com.vineyards.deerPlanner.guests.domain.GuestGroup;
import com.vineyards.deerPlanner.guests.domain.GuestRelationship;
import java.util.List;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jmolecules.architecture.hexagonal.SecondaryAdapter;
import org.springframework.stereotype.Component;

@Component
@SecondaryAdapter
@RequiredArgsConstructor
@Slf4j
public class GuestGroupRepositoryAdapter implements GuestGroupOutPort {

  private final GuestGroupJpaRepository jpa;

  @Override
  public GuestGroup create(GuestGroup group) {
    return toDomain(jpa.save(toEntity(group)));
  }

  @Override
  public GuestGroup update(GuestGroup group) {
    // Load the managed entity and mutate it in place: id is autogenerated (@XidId) so a plain
    // save() would already work via merge(), but loading first keeps createdAt/@PreUpdate
    // behaviour explicit and consistent with the other adapters that had to guard against it.
    GuestGroupEntity existing =
        jpa.findById(group.getId())
            .orElseThrow(
                () ->
                    new IllegalStateException("guest_group.update.not-found id=" + group.getId()));
    existing.setName(group.getName());
    existing.setRelationship(group.getRelationship().name());
    existing.setSharedEmail(group.getSharedEmail());
    existing.setSharedPhone(group.getSharedPhone());
    existing.setPrimaryGuestId(group.getPrimaryGuestId());
    existing.setInvitationToken(group.getInvitationToken());
    existing.setDisplayOrder(group.getDisplayOrder());
    return toDomain(jpa.save(existing));
  }

  @Override
  public Optional<GuestGroup> findById(String id) {
    return jpa.findById(id).map(GuestGroupRepositoryAdapter::toDomain);
  }

  @Override
  public List<GuestGroup> findByEventId(String eventId) {
    return jpa.findByEventIdOrderByDisplayOrderAscNameAsc(eventId).stream()
        .map(GuestGroupRepositoryAdapter::toDomain)
        .toList();
  }

  @Override
  public void deleteById(String id) {
    jpa.deleteById(id);
  }

  @Override
  public boolean existsByInvitationToken(String token) {
    return jpa.existsByInvitationToken(token);
  }

  @Override
  public Optional<GuestGroup> findByInvitationToken(String token) {
    return jpa.findByInvitationToken(token).map(GuestGroupRepositoryAdapter::toDomain);
  }

  static GuestGroup toDomain(GuestGroupEntity e) {
    return GuestGroup.builder()
        .id(e.getId())
        .eventId(e.getEventId())
        .name(e.getName())
        .relationship(GuestRelationship.fromString(e.getRelationship()))
        .sharedEmail(e.getSharedEmail())
        .sharedPhone(e.getSharedPhone())
        .primaryGuestId(e.getPrimaryGuestId())
        .invitationToken(e.getInvitationToken())
        .displayOrder(e.getDisplayOrder())
        .createdAt(e.getCreatedAt())
        .updatedAt(e.getUpdatedAt())
        .build();
  }

  static GuestGroupEntity toEntity(GuestGroup d) {
    GuestGroupEntity e = new GuestGroupEntity();
    e.setId(d.getId());
    e.setEventId(d.getEventId());
    e.setName(d.getName());
    e.setRelationship(d.getRelationship().name());
    e.setSharedEmail(d.getSharedEmail());
    e.setSharedPhone(d.getSharedPhone());
    e.setPrimaryGuestId(d.getPrimaryGuestId());
    e.setInvitationToken(d.getInvitationToken());
    e.setDisplayOrder(d.getDisplayOrder());
    e.setCreatedAt(d.getCreatedAt());
    e.setUpdatedAt(d.getUpdatedAt());
    return e;
  }
}
