server.port=8080

# Logging
logging.level.com.vineyards.deerPlanner=INFO

# Spring
spring.application.name=@project.artifactId@
spring.jmx.enabled=false

# Spring Web
spring.jackson.default-property-inclusion=always
spring.mvc.problemdetails.enabled=true
spring.threads.virtual.enabled=true

# Actuator Endpoints
management.endpoints.jmx.exposure.exclude=*
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true
info.app.name=${spring.application.name}
management.observations.annotations.enabled=true

# Metrics
management.otlp.metrics.export.enabled=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.metrics.tags.application=${spring.application.name}
management.metrics.tags.env=${env}

# Traces
management.tracing.export.otlp.enabled=false
management.otlp.metrics.export.base-time-unit=seconds

# Logs
management.logging.export.otlp.enabled=false

# JPA
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.batch_size=4
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=50

# HttpClient
spring.http.client.connect-timeout=15s
spring.http.client.read-timeout=15s
