/**
 * tools/gen-keys.ts
 *
 * Generates an ephemeral RS256 keypair for local development and writes
 * it to `apps/api/.env.local`. The private key never lives in the
 * committed `.env` file.
 *
 * Usage:
 *   pnpm gen:keys
 *
 * Output:
 *   - Updates apps/api/.env.local with JWT_PRIVATE_KEY_PEM
 *   - Prints the kid so you can sync JWT_KEY_ID if desired
 *
 * NOTE: This key is for LOCAL DEV ONLY. Production keys live in AWS
 * Secrets Manager (see ADR-05).
 */
import { generateKeyPairSync } from 'node:crypto';
import {
  existsSync,
  readFileSync,
  writeFileSync,
  appendFileSync,
} from 'node:fs';
import { resolve } from 'node:path';

const ENV_LOCAL_PATH = resolve(__dirname, '..', '.env.local');

function generatePem(): string {
  const { privateKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  // Collapse multi-line PEM into a single-line escaped string for .env
  return (privateKey as string)
    .trim()
    .split('\n')
    .join('\\n');
}

function buildEnvContent(): string {
  const header =
    '# apps/api/.env.local — gitignored. Regenerated by `pnpm gen:keys`.\n' +
    '# DO NOT COMMIT. PEM is single-line with \\n escapes.\n\n';
  const pem = generatePem();
  return header + `JWT_PRIVATE_KEY_PEM="${pem}"\n`;
}

function writeEnvLocal(): void {
  const content = buildEnvContent();
  writeFileSync(ENV_LOCAL_PATH, content, { encoding: 'utf-8' });
  console.log(`[gen-keys] Wrote ${ENV_LOCAL_PATH}`);
  console.log('[gen-keys] Tip: keep JWT_KEY_ID and JWT_ISSUER from .env.');
  console.log('[gen-keys] Restart pnpm start:dev to pick up the new key.');
}

function main(): void {
  if (existsSync(ENV_LOCAL_PATH)) {
    const existing = readFileSync(ENV_LOCAL_PATH, 'utf-8');
    if (existing.includes('JWT_PRIVATE_KEY_PEM=')) {
      console.warn(
        '[gen-keys] .env.local already has JWT_PRIVATE_KEY_PEM — overwriting.',
      );
    }
  }
  writeEnvLocal();
}

main();
