package com.vineyards.deerPlanner.events.outbound;

import com.vineyards.deerPlanner.events.application.port.EventFilter;
import com.vineyards.deerPlanner.events.application.port.EventOutPort;
import com.vineyards.deerPlanner.events.domain.Event;
import com.vineyards.deerPlanner.events.domain.EventStatus;
import com.vineyards.deerPlanner.events.domain.EventType;
import java.util.Optional;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.jmolecules.architecture.hexagonal.SecondaryAdapter;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Adapts {@link EventOutPort} to PostgreSQL via the {@code events} table only. Wedding-specific
 * state lives in the {@code wedding_events} table and is owned by {@link
 * WeddingEventRepositoryAdapter} — this adapter knows nothing about it, so the base event flow
 * stays generic.
 */
@Component
@SecondaryAdapter
@RequiredArgsConstructor
@Slf4j
public class EventRepositoryAdapter implements EventOutPort {

  private final EventJpaRepository eventJpa;

  @Override
  @Transactional
  public Event create(Event event) {
    // id is autogenerated (@XidId), so the domain object arrives with id == null and Spring
    // Data's isNew() check correctly triggers persist() — @CreatedDate/@LastModifiedDate populate
    // automatically. We still set them explicitly on the transient object as a defensive default
    // in case the listener is ever bypassed (e.g. in tests using a plain JPA save).
    EventEntity entity = toEntity(event);
    EventEntity saved = eventJpa.save(entity);
    return toDomain(saved);
  }

  @Override
  @Transactional
  public Event update(Event event) {
    // Load the managed entity and mutate it in place instead of merging a fresh transient
    // instance: guarantees createdAt is never touched and @LastModifiedDate/@PreUpdate fire
    // normally against the row already tracked by the persistence context.
    EventEntity existing =
        eventJpa
            .findById(event.getId())
            .orElseThrow(
                () -> new IllegalStateException("event.update.not-found id=" + event.getId()));
    existing.setOrganizerId(event.getOrganizerId());
    existing.setEventType(event.getEventType().name());
    existing.setTitle(event.getTitle());
    existing.setEventDate(event.getEventDate());
    existing.setStatus(event.getStatus().name());
    existing.setLocationsPayload(event.getLocationsPayload());
    existing.setProgramPayload(event.getProgramPayload());
    existing.setContactsPayload(event.getContactsPayload());
    EventEntity saved = eventJpa.save(existing);
    return toDomain(saved);
  }

  @Override
  @Transactional(readOnly = true)
  public Optional<Event> findById(String id) {
    return eventJpa.findById(id).map(this::toDomain);
  }

  @Override
  @Transactional(readOnly = true)
  public Page<Event> search(EventFilter filter, Pageable pageable) {
    return eventJpa.findAll(toSpecification(filter), pageable).map(this::toDomain);
  }

  /**
   * Translates the technology-agnostic {@link EventFilter} into a JPA {@link Specification}. Lives
   * in the adapter because {@code Specification} is a JPA construct and must not leak into the
   * application or port layers.
   */
  private static Specification<EventEntity> toSpecification(EventFilter filter) {
    Specification<EventEntity> spec = Specification.unrestricted();
    if (filter.organizerId() != null) {
      spec = spec.and((root, q, cb) -> cb.equal(root.get("organizerId"), filter.organizerId()));
    }
    if (filter.title() != null && !filter.title().isBlank()) {
      String pattern = "%" + filter.title().toLowerCase().trim() + "%";
      spec = spec.and((root, q, cb) -> cb.like(cb.lower(root.get("title")), pattern));
    }
    if (filter.status() != null && !filter.status().isBlank()) {
      spec = spec.and((root, q, cb) -> cb.equal(root.get("status"), filter.status()));
    }
    if (filter.eventType() != null && !filter.eventType().isBlank()) {
      spec = spec.and((root, q, cb) -> cb.equal(root.get("eventType"), filter.eventType()));
    }
    if (filter.eventDateFrom() != null) {
      spec =
          spec.and(
              (root, q, cb) ->
                  cb.greaterThanOrEqualTo(root.get("eventDate"), filter.eventDateFrom()));
    }
    if (filter.eventDateTo() != null) {
      spec =
          spec.and(
              (root, q, cb) -> cb.lessThanOrEqualTo(root.get("eventDate"), filter.eventDateTo()));
    }
    return spec;
  }

  @Override
  @Transactional(readOnly = true)
  public java.util.List<Event> findByOrganizerId(String organizerId) {
    return eventJpa.findByOrganizerIdOrderByEventDateDesc(organizerId).stream()
        .map(this::toDomain)
        .toList();
  }

  @Override
  @Transactional
  public void deleteById(String id) {
    eventJpa.deleteById(id);
  }

  private Event toDomain(EventEntity entity) {
    return new Event(
        entity.getId(),
        entity.getOrganizerId(),
        EventType.fromString(entity.getEventType()),
        entity.getTitle(),
        entity.getEventDate(),
        EventStatus.valueOf(entity.getStatus()),
        entity.getLocationsPayload(),
        entity.getProgramPayload(),
        entity.getContactsPayload(),
        entity.getCreatedAt(),
        entity.getUpdatedAt());
  }

  // Only used by create(): id is null here, so this is always a genuinely new, transient
  // instance and Spring Data's isNew() check correctly routes it through persist().
  private EventEntity toEntity(Event event) {
    EventEntity entity = new EventEntity();
    entity.setId(event.getId());
    entity.setOrganizerId(event.getOrganizerId());
    entity.setEventType(event.getEventType().name());
    entity.setTitle(event.getTitle());
    entity.setEventDate(event.getEventDate());
    entity.setStatus(event.getStatus().name());
    entity.setLocationsPayload(event.getLocationsPayload());
    entity.setProgramPayload(event.getProgramPayload());
    entity.setContactsPayload(event.getContactsPayload());
    entity.setCreatedAt(event.getCreatedAt());
    entity.setUpdatedAt(event.getUpdatedAt());
    return entity;
  }
}
